export const PROJECTS = [     
    {
        id: 1,
        title: "Mern.In",
        image: "/assets/projects/mern.svg",
        description: "Aplicação que utiliza do pack MERN de stacks para sua estruturação. oAuth de usuário, permitindo cadastro de suas informações no banco de dados (mongo-db) e armazenando o Store de suas atividades a partir da biblioteca Redux.",
        stack: [
            "redux", "react", "javascript", "mui", "node", "mongo-db", "express"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark-duble",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Mern.In",
        deploy: "",
    },    
    {
        id: 2,
        title: "HighTrip",
        image: "/assets/projects/hightrip.svg",
        description: "Landing Page para um App de viagens e aventura. Com UX/UI Design responsivo e atrativo, utilizando o método 'Mobile-First' do Framework Tailwind para foco maior na responsividade. Next.Js e TypeScript para componentização e uso de Props.",
        stack: [
            "nextjs", "react", "typescript", "react-icons", "tailwind"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/HighTrip",
        deploy: "https://hightrip.vercel.app/",
    },      
    {
        id: 3,
        title: "To Do List",
        image: "/assets/projects/todolist.svg",
        description: "Projeto de uma To-Do list, utilizando o framework 'Vite' para React como base do desenvolvimento, trazendo layout responsivo e intuitivo. Podendo pesquisar tasks feitas e não feitas, filtrar por tarefas como 'Pessoais', 'Trabalho', 'Contas' e 'Estudos'.",
        stack: [
            "vite", "react", "javascript", "react-icons", "css", "html", "github"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/ToDoList",    
        deploy: "https://todolist-arthur.vercel.app/",
    },
    {
        id: 4,
        title: "Malta University",
        image: "/assets/projects/malta.svg",
        description: "Este projeto consiste em uma Landing Page para a área de cursos industriais de uma Universidade. Todo o UI Design foi feito por 'Maham Bukhari' em seu perfil no Behance.",
        stack: [
            "vite", "react", "router", "javascript", "css", "html", "github"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/University-Of-Malta",
        deploy: "https://university-of-malta.vercel.app/",
    },    
    {
        id: 5,
        title: "Nike Store",
        image: "/assets/projects/nike.svg",
        description: "E-commerce com estética e produtos da Nike que possui sua base em Vite JS, React Js e Tailwind. Responsivo para dispositivos, com tema Dark e 'carrinho' que é atualizado de acordo com quantidade e tamanho.",
        stack: [
            "vite", "react", "javascript", "react-icons", "font-awesome", "tailwind", "theme"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Nike",
        deploy: "https://nike-air.vercel.app/",
    },
    {
        id: 6,
        title: "Crud SQL",
        image: "/assets/projects/crud.svg",
        description: "CRUD é um acrônimo para as operações fundamentais em qualquer sistema que interage com um banco de dados: Create (Criar), Read (Ler), Update (Atualizar) e Delete (Apagar).",
        stack: [
            "vite", "react", "javascript", "mysql", "node", "axios", "express"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark-duble",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/ToDoList",
        deploy: "",
    },    
    {
        id: 7,
        title: "Beats by Dre",
        image: "/assets/projects/beats.svg",
        description: "Landing Page para marca Beats, possuindo animações dinâmicas por meio da tecnologia ScrollReveal.Js, UX/UI Design moderno e responsivo para diversos tamanhos de Smartphones.",
        stack: [
            "vite", "react", "javascript", "scrollreveal", "react-icons", "sass", "css"
        ],
        // markfront: "/assets/projects/mark_front.svg",
        // markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Beats",
        deploy: "https://beats-arthur.vercel.app/",
    },
    {
        id: 8,
        title: "Dashboard Co2",
        image: "/assets/projects/dash_co2.svg",
        description: "Dashboard interativo que permite escoher as décadas e anos em que queira analisar as emições de carbono por cada região do mundo, indo de continentes até mesmo a países. Utilizando arquivo .csv para extração de dados.",
        stack: [
            "jupyter", "python", "panel", "hvplot", "colab", "csv"
        ],
        // markfront: "",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurDSant/Dash-Co2_Emission",
        deploy: "",
    },
    {
        id: 9,
        title: "DA - Gestão de vendas",
        image: "/assets/projects/bi_sm.svg",
        description: "Este projeto é um dashboard interativo projetado para visualização e apresentação de dados, visando apoiar a tomada de decisão. Utilizando banco de dados .xlsx com tratamento de dados e curadoria de área.",
        stack: [
            "power-bi", "excel", "figma",
        ],
        // markfront: "",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurDSant/BI-Sales_Management",
        deploy: "",
    },
    {
        id: 10,
        title: "DA - Material agrícula",
        image: "/assets/projects/da_agricula.svg",
        description: "Este projeto Python realiza a análise e visualização dos dados de preços de matérias-primas agrícolas usando um banco de dados do Kaggle com arquivo no formato .csv. Estruturado no Jupyter-Notebook e compatível para Google Colab",
        stack: [
            "jupyter", "python", "pandas", "numpy", "seaborn", "matplotlib", "colab"
        ],
        // markfront: "",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/DataAnalysis-Agricultural_Raw_Material",
        deploy: "",
    },
    {
        id: 11,
        title: "API RestFull",
        image: "/assets/projects/fastapi.svg",
        description: "API RestFull utilizando Python como base, possuindo as funções GET, POST, PUT, UPDATE e DELETE. Com implementação de pesquisa por categorias como nos exemplos do arquivo Test_Server.py no repositório.",
        stack: [
            "python", "fast-api", "postman"
        ],
        // markfront: "",
        // markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/API-RestFull",
        deploy: "",
    },
];