export const PROJECTS = [
    {
        id: 1,
        title: "HighTrip",
        image: "/assets/projects/hightrip.svg",
        description: "Landing Page para um App de viagens e aventura. Com UX/UI Design responsivo e atrativo, utilizando o método 'Mobile-First' do Framework Tailwind para foco maior na responsividade. Next.Js e TypeScript para componentização e uso de Props.",
        stack: [
            "nextjs", "react", "typescript", "react-icons", "tailwind"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/HighTrip",
        deploy: "https://hightrip.vercel.app/",

    },
    {
        id: 2,
        title: "To Do List",
        image: "/assets/projects/todolist.svg",
        description: "Projeto de uma To-Do list, utilizando o framework 'Vite' para React como base do desenvolvimento, trazendo layout responsivo e intuitivo. Podendo pesquisar tasks feitas e não feitas, filtrar por tarefas como 'Pessoais', 'Trabalho', 'Contas' e 'Estudos'.",
        stack: [
            "vite", "react", "javascript", "react-icons", "css", "html", "github"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/ToDoList",    
        deploy: "https://todolist-arthur.vercel.app/",
    },
    {
        id: 4,
        title: "Mern.In",
        image: "/assets/projects/mern.svg",
        description: "Aplicação que utiliza do pack MERN de stacks para sua estruturação. oAuth de usuário, permitindo cadastro de suas informações no banco de dados (mongo-db) e armazenando o Store de suas atividades a partir da biblioteca Redux.",
        stack: [
            "redux", "react", "javascript", "mui", "node", "mongo-db", "express", "theme"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark-duble",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Mern.In",
        deploy: "",
    },
    {
        id: 5,
        title: "Crud SQL",
        image: "/assets/projects/crud.svg",
        description: "CRUD é um acrônimo para as operações fundamentais em qualquer sistema que interage com um banco de dados: Create (Criar), Read (Ler), Update (Atualizar) e Delete (Apagar).",
        stack: [
            "vite", "react", "javascript", "mysql", "node", "nodemon", "axios", "express"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark-duble",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/ToDoList",
        deploy: "",
    },
    {
        id: 5,
        title: "Malta University",
        image: "/assets/projects/malta.svg",
        description: "Este projeto consiste em uma Landing Page para a área de cursos industriais de uma Universidade. Todo o UI Design foi feito por 'Maham Bukhari' em seu perfil no Behance.",
        stack: [
            "vite", "react", "router", "javascript", "css", "html", "github"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/University-Of-Malta",
        deploy: "https://university-of-malta.vercel.app/",
    },
    {
        id: 6,
        title: "Nike Store",
        image: "/assets/projects/nike.svg",
        description: "E-commerce com estética e produtos da Nike que possui sua base em Vite JS, React Js e Tailwind. Responsivo para dispositivos, com tema Dark e 'carrinho' que é atualizado de acordo com quantidade e tamanho.",
        stack: [
            "vite", "react", "javascript", "react-icons", "font-awesome", "tailwind", "theme"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Nike",
        deploy: "https://nike-air.vercel.app/",
    },
    {
        id: 7,
        title: "Beats",
        image: "/assets/projects/beats.svg",
        description: "Landing Page para marca Beats, possuindo animações dinâmicas por meio da tecnologia ScrollReveal.Js, UX/UI Design moderno e responsivo para diversos tamanhos de Smartphones.",
        stack: [
            "vite", "react", "javascript", "scrollreveal", "react-icons", "sass", "css"
        ],
        markfront: "/assets/projects/mark_front.svg",
        markback: "",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/Beats",
        deploy: "https://beats-arthur.vercel.app/",
    },
    {
        id: 8,
        title: "API RestFull",
        image: "/assets/projects/fastapi.svg",
        description: "API RestFull utilizando Python como base, possuindo as funções GET, POST, PUT, UPDATE e DELETE. Com implementação de pesquisa por categorias como nos exemplos do arquivo Test_Server.py no repositório.",
        stack: [
            "python", "fast-api", "postman"
        ],
        markfront: "",
        markback: "/assets/projects/mark_back.svg",
        classMark: "project-mark",
        none: "",
        class: "project",
        classReverse: "project reverse",
        classButton: "button-project deploy-btn",
        classButtonCant: "button-project deploy-btn cant-btn",
        github: "https://github.com/ArthurSantDev/API-RestFull",
        deploy: "",
    },
];