export const STACKS = [
  { id: 0, src: "/assets/stacks/javascript.svg", alt: "JavaScript" },
  { id: 1, src: "/assets/stacks/typescript.svg", alt: "TypeScript" },   
  { id: 2, src: "/assets/stacks/node.svg", alt: "Node.js" },
  { id: 3, src: "/assets/stacks/nodemon.svg", alt: "Nodemon" },
  { id: 4, src: "/assets/stacks/axios.svg", alt: "Axios" },
  { id: 5, src: "/assets/stacks/express.svg", alt: "Express.js" },

  { id: 6, src: "/assets/stacks/python.svg", alt: "Python" },
  { id: 7, src: "/assets/stacks/django.svg", alt: "Django" },
  { id: 8, src: "/assets/stacks/pandas.svg", alt: "Pandas" },
  { id: 9, src: "/assets/stacks/numpy.svg", alt: "Numpy" },
  { id: 10, src: "/assets/stacks/panel.svg", alt: "Panel" },
  { id: 11, src: "/assets/stacks/hvplot.svg", alt: "hvplot" },
  { id: 12, src: "/assets/stacks/fast-api.svg", alt: "FastAPI" },
  { id: 13, src: "/assets/stacks/jupyter.svg", alt: "Jupyter-Notebook" },
  { id: 14, src: "/assets/stacks/colab.svg", alt: "Colab" },
  { id: 15, src: "/assets/stacks/postman.svg", alt: "Postman" },
  { id: 16, src: "/assets/stacks/matplotlib.svg", alt: "Matplotlib" },
  { id: 17, src: "/assets/stacks/seaborn.svg", alt: "Seaborn" },
  { id: 18, src: "/assets/stacks/r.svg", alt: "R programming language" },
  { id: 19, src: "/assets/stacks/power-bi.svg", alt: "Power BI" },
  { id: 20, src: "/assets/stacks/java.svg", alt: "Java" },
  { id: 21, src: "/assets/stacks/oracle.svg", alt: "Oracle" },
  { id: 22, src: "/assets/stacks/php.svg", alt: "PHP" },
  { id: 23, src: "/assets/stacks/postgre.svg", alt: "PostgreSQL" },
  { id: 24, src: "/assets/stacks/phpstorm.svg", alt: "PhpStorm" },
  { id: 25, src: "/assets/stacks/mongo-db.svg", alt: "MongoDB" },
  { id: 26, src: "/assets/stacks/sql.svg", alt: "SQL" },
  { id: 27, src: "/assets/stacks/mysql.svg", alt: "MySQL" },
  { id: 28, src: "/assets/stacks/sqlite.svg", alt: "SQLite" },

  { id: 29, src: "/assets/stacks/vite.svg", alt: "Vite" },
  { id: 30, src: "/assets/stacks/react.svg", alt: "React" },
  { id: 31, src: "/assets/stacks/react bootstrap.svg", alt: "React Bootstrap" },
  { id: 32, src: "/assets/stacks/router.svg", alt: "React Router" },
  { id: 33, src: "/assets/stacks/nextjs.svg", alt: "Next.js" },
  { id: 34, src: "/assets/stacks/vue.svg", alt: "Vue.js" },
  { id: 35, src: "/assets/stacks/redux.svg", alt: "Redux" },
  { id: 36, src: "/assets/stacks/theme.svg", alt: "Theming" },
  { id: 37, src: "/assets/stacks/scrollreveal.svg", alt: "ScrollReveal" },
  { id: 38, src: "/assets/stacks/react-icons.svg", alt: "React Icons" },
  { id: 39, src: "/assets/stacks/mui.svg", alt: "Material-UI" },
  { id: 40, src: "/assets/stacks/tailwind.svg", alt: "Tailwind CSS" },
  { id: 41, src: "/assets/stacks/sass.svg", alt: "Sass" },
  { id: 42, src: "/assets/stacks/bootstrap.svg", alt: "Bootstrap" },
  
  { id: 43, src: "/assets/stacks/html.svg", alt: "HTML" },
  { id: 44, src: "/assets/stacks/css.svg", alt: "CSS" },
  
  { id: 45, src: "/assets/stacks/powershell.svg", alt: "PowerShell" },
  { id: 46, src: "/assets/stacks/git.svg", alt: "Git" },
  { id: 47, src: "/assets/stacks/github.svg", alt: "GitHub" },
  { id: 48, src: "/assets/stacks/github-vs.svg", alt: "GitHub VS Code" },
  { id: 49, src: "/assets/stacks/gitlab.svg", alt: "GitLab" },
  { id: 50, src: "/assets/stacks/vercel.svg", alt: "Vercel" },

  { id: 200, src: "/assets/stacks/csv.svg", alt: "csv" },
];