export const STACKS = [
   { id: 1, src: "/assets/stacks/dribbble.svg", alt: "Dribbble logo" },
   { id: 2, src: "/assets/stacks/figma.svg", alt: "Figma logo" },
   { id: 3, src: "/assets/stacks/html.svg", alt: "HTML logo" },
   { id: 4, src: "/assets/stacks/css.svg", alt: "CSS logo" },
   { id: 5, src: "/assets/stacks/javascript.svg", alt: "JavaScript logo" },
   { id: 6, src: "/assets/stacks/typescript.svg", alt: "TypeScript logo" },
   { id: 7, src: "/assets/stacks/vite.svg", alt: "Vite logo" },
   { id: 8, src: "/assets/stacks/react.svg", alt: "React logo" },
   { id: 9, src: "/assets/stacks/react bootstrap.svg", alt: "React Bootstrap logo" },
   { id: 10, src: "/assets/stacks/router.svg", alt: "React Router logo" },

   { id: 11, src: "/assets/stacks/nextjs.svg", alt: "Next.js logo" },
   { id: 12, src: "/assets/stacks/vue.svg", alt: "Vue.js logo" },
   { id: 13, src: "/assets/stacks/redux.svg", alt: "Redux logo" },
   { id: 14, src: "/assets/stacks/theme.svg", alt: "Theming logo" },
   { id: 15, src: "/assets/stacks/scrollreveal.svg", alt: "ScrollReveal logo" },
   { id: 16, src: "/assets/stacks/react-icons.svg", alt: "React Icons logo" },
   { id: 17, src: "/assets/stacks/mui.svg", alt: "Material-UI logo" },
   { id: 18, src: "/assets/stacks/tailwind.svg", alt: "Tailwind CSS logo" },
   { id: 19, src: "/assets/stacks/sass.svg", alt: "Sass logo" },
   { id: 20, src: "/assets/stacks/bootstrap.svg", alt: "Bootstrap logo" },
   
   { id: 21, src: "/assets/stacks/python.svg", alt: "Python logo" },
   { id: 22, src: "/assets/stacks/django.svg", alt: "Django logo" },
   { id: 23, src: "/assets/stacks/pandas.svg", alt: "Pandas logo" },
   { id: 24, src: "/assets/stacks/fast-api.svg", alt: "FastAPI logo" },
   { id: 25, src: "/assets/stacks/postman.svg", alt: "Postman" },
   { id: 26, src: "/assets/stacks/r.svg", alt: "R programming language logo" },
   { id: 27, src: "/assets/stacks/power-bi.svg", alt: "Power BI logo" },
   { id: 28, src: "/assets/stacks/java.svg", alt: "Java logo" },
   { id: 29, src: "/assets/stacks/oracle.svg", alt: "Oracle logo" },
   { id: 30, src: "/assets/stacks/php.svg", alt: "PHP logo" },

   { id: 31, src: "/assets/stacks/postgre.svg", alt: "PostgreSQL logo" },
   { id: 32, src: "/assets/stacks/phpstorm.svg", alt: "PhpStorm logo" },
   { id: 33, src: "/assets/stacks/node.svg", alt: "Node.js logo" },
   { id: 34, src: "/assets/stacks/nodemon.svg", alt: "Nodemon logo" },
   { id: 35, src: "/assets/stacks/axios.svg", alt: "Axios logo" },
   { id: 36, src: "/assets/stacks/express.svg", alt: "Express.js logo" },
   { id: 37, src: "/assets/stacks/mongo-db.svg", alt: "MongoDB logo" },
   { id: 38, src: "/assets/stacks/sql.svg", alt: "SQL logo" },
   { id: 39, src: "/assets/stacks/mysql.svg", alt: "MySQL logo" },
   { id: 40, src: "/assets/stacks/sqlite.svg", alt: "SQLite logo" },
   
   { id: 41, src: "/assets/stacks/powershell.svg", alt: "PowerShell logo" },
   { id: 42, src: "/assets/stacks/git.svg", alt: "Git logo" },
   { id: 43, src: "/assets/stacks/github.svg", alt: "GitHub logo" },
   { id: 44, src: "/assets/stacks/github-vs.svg", alt: "GitHub VS Code logo" },
   { id: 45, src: "/assets/stacks/gitlab.svg", alt: "GitLab logo" },
   { id: 46, src: "/assets/stacks/vercel.svg", alt: "Vercel logo" }
 ];